from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '27941396bf5d'
down_revision: Union[str, None] = '3521b9391832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # Ensure that there is an index on the event_id column in the events table
    op.create_index('ix_events_event_id', 'events', ['event_id'], unique=False)

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id']),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )

    # Other column modifications, if needed
    op.add_column('events', sa.Column('user_id', sa.String(length=36), nullable=False))
    op.add_column('events', sa.Column('start_time', sa.Time(), nullable=False))
    op.add_column('events', sa.Column('end_time', sa.Time(), nullable=False))
    op.add_column('events', sa.Column('event_type', sa.String(length=50), nullable=False))
    op.add_column('events', sa.Column('event_category', sa.String(length=100), nullable=False))
    op.add_column('events', sa.Column('state', sa.String(length=100), nullable=False))
    op.add_column('events', sa.Column('city', sa.String(length=100), nullable=False))
    op.add_column('events', sa.Column('organization_name', sa.String(length=255), nullable=False))
    op.add_column('events', sa.Column('organization_contact', sa.String(length=255), nullable=False))

def downgrade() -> None:
    # Remove the event_documents table
    op.drop_table('event_documents')

    # Remove the added columns
    op.drop_column('events', 'user_id')
    op.drop_column('events', 'start_time')
    op.drop_column('events', 'end_time')
    op.drop_column('events', 'event_type')
    op.drop_column('events', 'event_category')
    op.drop_column('events', 'state')
    op.drop_column('events', 'city')
    op.drop_column('events', 'organization_name')
    op.drop_column('events', 'organization_contact')
    op.drop_column('events', 'event_status')
