"""Add event_id

Revision ID: 3521b9391832
Revises: 5b73b75006ae
Create Date: 2024-09-07 14:59:47.699475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3521b9391832'
down_revision: Union[str, None] = '5b73b75006ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('event_id', sa.String(length=36), nullable=False))
    op.add_column('events', sa.Column('event_status', sa.String(length=36), nullable=False))


def downgrade() -> None:
    pass
