"""add eventpolicy table

Revision ID: 8fde3d3afded
Revises: 7139af0ed562
Create Date: 2024-09-15 15:26:30.418798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8fde3d3afded'
down_revision: Union[str, None] = '7139af0ed562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_policies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('event_visibility', sa.Boolean(), nullable=False),
    sa.Column('participant_list_visibility', sa.String(length=50), nullable=False),
    sa.Column('cpf_validation', sa.Boolean(), nullable=False),
    sa.Column('allow_third_party_registration', sa.Boolean(), nullable=False),
    sa.Column('has_age_limit', sa.Boolean(), nullable=False),
    sa.Column('age_min', sa.Integer(), nullable=True),
    sa.Column('age_max', sa.Integer(), nullable=True),
    sa.Column('allow_transfer', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('policy_id')
    )



def downgrade() -> None:
    pass
